// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-models.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_models_default = defineTool({
  name: "search_models",
  title: "Search shoe models",
  description: "Search the Shoe Sherpa catalog for running shoe models by name, optionally filtered by brand or category. Returns id, full name, aggregate rating, and review count.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Model name or partial name to search for."),
    brand: z.string().trim().optional().describe("Optional brand name filter (case-insensitive)."),
    category: z.string().trim().optional().describe("Optional category filter (e.g. road, trail, race)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, brand, category, limit }) => {
    const supabase = sb();
    let q = supabase.from("models").select("id,name,category,msrp,image_url,brand:brands(id,name)").ilike("name", `%${query}%`).limit(limit ?? 20);
    if (category) q = q.ilike("category", `%${category}%`);
    const { data: models, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let filtered = models ?? [];
    if (brand) {
      const b = brand.toLowerCase();
      filtered = filtered.filter((m) => m.brand?.name?.toLowerCase().includes(b));
    }
    const ids = filtered.map((m) => m.id);
    const { data: summaries } = ids.length ? await supabase.from("model_summaries").select("model_id,avg_rating,review_count").in("model_id", ids) : { data: [] };
    const summaryMap = new Map((summaries ?? []).map((s) => [s.model_id, s]));
    const rows = filtered.map((m) => {
      const s = summaryMap.get(m.id);
      return {
        id: m.id,
        name: [m.brand?.name, m.name].filter(Boolean).join(" "),
        brand: m.brand?.name ?? null,
        category: m.category ?? null,
        msrp: m.msrp ?? null,
        image_url: m.image_url ?? null,
        avg_rating: s?.avg_rating ?? null,
        review_count: s?.review_count ?? 0,
        url: `https://shoe-sherpa.com/model/${m.id}`
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { results: rows }
    };
  }
});

// src/lib/mcp/tools/get-model.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_model_default = defineTool2({
  name: "get_model",
  title: "Get shoe model detail",
  description: "Fetch the full spec sheet, aggregate rating, and up to 20 verified reviews for a specific shoe model by id.",
  inputSchema: {
    model_id: z2.string().uuid().describe("Model id (uuid)."),
    review_limit: z2.number().int().min(0).max(50).optional().describe("How many reviews to include (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ model_id, review_limit }) => {
    const supabase = sb2();
    const [{ data: model, error: mErr }, { data: summary }, { data: reviews }] = await Promise.all([
      supabase.from("models").select("id,name,image_url,category,release_year,weight_g,drop_mm,stack_height_mm,msrp,updated_at,brand:brands(id,name,notes)").eq("id", model_id).maybeSingle(),
      supabase.from("model_summaries").select("avg_rating,review_count,summary").eq("model_id", model_id).maybeSingle(),
      supabase.from("reviews").select("rating,content,created_at,profile:profiles(display_name,username)").eq("model_id", model_id).order("created_at", { ascending: false }).limit(review_limit ?? 20)
    ]);
    if (mErr || !model) {
      return { content: [{ type: "text", text: `Model not found: ${mErr?.message ?? model_id}` }], isError: true };
    }
    const brand = model.brand;
    const payload = {
      id: model.id,
      name: [brand?.name, model.name].filter(Boolean).join(" "),
      brand: brand ? { id: brand.id, name: brand.name, notes: brand.notes ?? null } : null,
      category: model.category,
      release_year: model.release_year,
      weight_g: model.weight_g,
      drop_mm: model.drop_mm,
      stack_height_mm: model.stack_height_mm,
      msrp: model.msrp,
      image_url: model.image_url,
      updated_at: model.updated_at,
      aggregate: summary ? { avg_rating: summary.avg_rating, review_count: summary.review_count, summary: summary.summary } : null,
      reviews: (reviews ?? []).map((r) => ({
        author: r.profile?.display_name || r.profile?.username || "Runner",
        rating: r.rating,
        date: r.created_at?.slice(0, 10) ?? null,
        content: r.content
      })),
      url: `https://shoe-sherpa.com/model/${model.id}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-reviews.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
function sb3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_reviews_default = defineTool3({
  name: "list_reviews",
  title: "List reviews for a model",
  description: "Paginate through every verified review for a given model, newest first.",
  inputSchema: {
    model_id: z3.string().uuid().describe("Model id (uuid)."),
    limit: z3.number().int().min(1).max(100).optional().describe("Page size (default 50)."),
    offset: z3.number().int().min(0).optional().describe("Offset for pagination (default 0).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ model_id, limit, offset }) => {
    const supabase = sb3();
    const l = limit ?? 50;
    const o = offset ?? 0;
    const { data, error, count } = await supabase.from("reviews").select("rating,content,created_at,profile:profiles(display_name,username)", { count: "exact" }).eq("model_id", model_id).order("created_at", { ascending: false }).range(o, o + l - 1);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      author: r.profile?.display_name || r.profile?.username || "Runner",
      rating: r.rating,
      date: r.created_at?.slice(0, 10) ?? null,
      content: r.content
    }));
    const payload = { total: count ?? rows.length, offset: o, limit: l, reviews: rows };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/best-for.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
function sb4() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var best_for_default = defineTool4({
  name: "best_for",
  title: "Best shoes for a runner segment",
  description: "Return the ranked shortlist of shoes for a given runner segment (e.g. 'marathon-wide-feet', 'trail-50k-neutral'). Uses only models with at least 10 verified reviews in that segment.",
  inputSchema: {
    segment_slug: z4.string().trim().min(1).describe("Segment slug \u2014 see the segments list at /best."),
    limit: z4.number().int().min(1).max(20).optional().describe("Top N results (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ segment_slug, limit }) => {
    const supabase = sb4();
    const [{ data: seg }, { data: stats, error }] = await Promise.all([
      supabase.from("segments").select("slug,title,description").eq("slug", segment_slug).maybeSingle(),
      supabase.from("model_segment_stats").select("model_id,avg_rating,review_count").eq("segment_slug", segment_slug).gte("review_count", 10).order("avg_rating", { ascending: false }).limit(limit ?? 5)
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!seg) return { content: [{ type: "text", text: `Unknown segment: ${segment_slug}` }], isError: true };
    const ids = (stats ?? []).map((s) => s.model_id);
    const { data: models } = ids.length ? await supabase.from("models").select("id,name,image_url,msrp,brand:brands(id,name)").in("id", ids) : { data: [] };
    const modelMap = new Map((models ?? []).map((m) => [m.id, m]));
    const rows = (stats ?? []).map((s, i) => {
      const m = modelMap.get(s.model_id);
      if (!m) return null;
      return {
        rank: i + 1,
        model_id: m.id,
        name: [m.brand?.name, m.name].filter(Boolean).join(" "),
        avg_rating: s.avg_rating,
        review_count: s.review_count,
        msrp: m.msrp ?? null,
        image_url: m.image_url ?? null,
        url: `https://shoe-sherpa.com/model/${m.id}`
      };
    }).filter(Boolean);
    const payload = { segment: seg, results: rows };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-brand-facts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
function sb5() {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_brand_facts_default = defineTool5({
  name: "get_brand_facts",
  title: "Get verified brand facts",
  description: "Return the verified brand notes (fit, width options, technology claims) that Shoe Sherpa treats as source of truth for a brand. Look up by brand id OR brand name.",
  inputSchema: {
    brand_id: z5.string().uuid().optional().describe("Brand id (uuid). Preferred."),
    brand_name: z5.string().trim().optional().describe("Brand name (case-insensitive) if id not known.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ brand_id, brand_name }) => {
    if (!brand_id && !brand_name) {
      return { content: [{ type: "text", text: "Provide brand_id or brand_name" }], isError: true };
    }
    const supabase = sb5();
    let q = supabase.from("brands").select("id,name,notes,facts_updated_at,updated_at").limit(1);
    if (brand_id) q = q.eq("id", brand_id);
    else if (brand_name) q = q.ilike("name", brand_name);
    const { data, error } = await q.maybeSingle();
    if (error || !data) {
      return { content: [{ type: "text", text: `Brand not found: ${error?.message ?? brand_id ?? brand_name}` }], isError: true };
    }
    const payload = {
      id: data.id,
      name: data.name,
      notes: data.notes ?? null,
      facts_updated_at: data.facts_updated_at ?? null,
      url: `https://shoe-sherpa.com/brand/${data.id}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "shoe-sherpa-mcp",
  title: "Shoe Sherpa",
  version: "0.1.0",
  instructions: "Query the Shoe Sherpa catalog of community-verified running shoe reviews. Use search_models to find shoes by name, get_model for full detail + reviews, list_reviews to paginate every verified review, best_for for ranked shortlists per runner segment, and get_brand_facts for verified brand fit/tech notes. All data is public.",
  tools: [search_models_default, get_model_default, list_reviews_default, best_for_default, get_brand_facts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
